### PR TITLE
Adding Reset EEPROM feature

### PR DESCRIPTION
**Pull request by hanhha**
This feature would be helpful in case of Delta style printer which requires bed leveling frequently and EEPROM parameters would be modified multiple times.

### CODE REVIEW

**Comment by Salandora** [comment]
Nice,
good idea to add this.

I just have one concern with it, what if someone accidently hit this button?
Can you please add a "Are you sure?" dialog to it.

**Comment by hanhha** [comment]
That's what I intended to do. However I just didn't know how to implement this :disappointed:

**Comment by Salandora** [comment]
Uhm well check how it is done in the octoprint core xD thats the easiest and most compatible way :-)
The cancel button should be a good starting point.

**Comment by hanhha** [comment]
Well, added confirm dialog and notifier. Fortunately that code snippet is in the firmware updater plugin which I'm using frequently :rocket:

**Comment by Salandora** [comment]
Alright will take a look in the next days and if everything works I'm merging it.

**Comment by Salandora** [comment]
Alright I couldn't resist to take a quick look and noticed 2-3 things right away ^^ maybe you like to take a look at it and leave a comment.

**Comment by Salandora** [comment]
First off I'm sorry I completely forgot about your PR.
Do you like to fix the changed line?
I also would like the oncancel to be remove because it has no use actually. If someone needs it it is easily readded.

If you do not have  time for thise 2 changed no problem I can easily merge it and make the changes on my own :-)

**Comment by hanhha** [comment]
Hi,
I'm currently away from my home (and my printer :( ) so that I can not make changes recently days (I always feel not safe to check in code without retrying ☠️ ). So you do me a favor if you can help me to change it.
However, I'm planing to add import/export file function. I might make a new PR for that :D

**Comment by Salandora** [comment]
Alright, I'll gonna merge it and make the changes.
Import/Export feature sounds nice, and yes please as a separate PR.

**Pull request merged**
